config/routes.rb
Cannelle::Application.routes.draw do
  
  devise_for :users, :path_names => { :sign_up => "inscription", :sign_in => "identification"}

  resources :invitations

  resources :ambiances

  resources :cuisines

  match '/contact',   :to => 'pages#contact'
  match '/about',     :to => 'pages#about'
  match '/aide',      :to => 'pages#aide'
  match '/invitations', :to => 'invitations#index'
  
  root :to => 'pages#home'  
  

end

app/models/ambiance.rb
class Ambiance < ActiveRecord::Base
  has_and_belongs_to_many :invitations
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_and_belongs_to_many :invitations
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  has_and_belongs_to_many :cuisines
  has_and_belongs_to_many :ambiances
  validates_presence_of :name, :date, :description, :convives, :price
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, #:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation
end

app/controllers/ambiances_controller.rb
class AmbiancesController < ApplicationController
  # GET /ambiances
  # GET /ambiances.xml
  def index
    @ambiances = Ambiance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ambiances }
    end
  end

  # GET /ambiances/1
  # GET /ambiances/1.xml
  def show
    @ambiance = Ambiance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ambiance }
    end
  end

  # GET /ambiances/new
  # GET /ambiances/new.xml
  def new
    @ambiance = Ambiance.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ambiance }
    end
  end

  # GET /ambiances/1/edit
  def edit
    @ambiance = Ambiance.find(params[:id])
  end

  # POST /ambiances
  # POST /ambiances.xml
  def create
    @ambiance = Ambiance.new(params[:ambiance])

    respond_to do |format|
      if @ambiance.save
        format.html { redirect_to(@ambiance, :notice => 'L ambiance a ete creee.') }
        format.xml  { render :xml => @ambiance, :status => :created, :location => @ambiance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ambiance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ambiances/1
  # PUT /ambiances/1.xml
  def update
    @ambiance = Ambiance.find(params[:id])

    respond_to do |format|
      if @ambiance.update_attributes(params[:ambiance])
        format.html { redirect_to(@ambiance, :notice => 'L ambiance a ete modifiee.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ambiance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ambiances/1
  # DELETE /ambiances/1.xml
  def destroy
    @ambiance = Ambiance.find(params[:id])
    @ambiance.destroy

    respond_to do |format|
      format.html { redirect_to(ambiances_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  # GET /cuisines
  # GET /cuisines.xml
  def index
    @cuisines = Cuisine.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @cuisines }
    end
  end

  # GET /cuisines/1
  # GET /cuisines/1.xml
  def show
    @cuisine = Cuisine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cuisine }
    end
  end

  # GET /cuisines/new
  # GET /cuisines/new.xml
  def new
    @cuisine = Cuisine.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cuisine }
    end
  end

  # GET /cuisines/1/edit
  def edit
    @cuisine = Cuisine.find(params[:id])
  end

  # POST /cuisines
  # POST /cuisines.xml
  def create
    @cuisine = Cuisine.new(params[:cuisine])

    respond_to do |format|
      if @cuisine.save
        format.html { redirect_to(@cuisine, :notice => 'Cuisine was successfully created.') }
        format.xml  { render :xml => @cuisine, :status => :created, :location => @cuisine }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cuisine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cuisines/1
  # PUT /cuisines/1.xml
  def update
    @cuisine = Cuisine.find(params[:id])

    respond_to do |format|
      if @cuisine.update_attributes(params[:cuisine])
        format.html { redirect_to(@cuisine, :notice => 'Cuisine was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cuisine.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cuisines/1
  # DELETE /cuisines/1.xml
  def destroy
    @cuisine = Cuisine.find(params[:id])
    @cuisine.destroy

    respond_to do |format|
      format.html { redirect_to(cuisines_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.xml
  
  def index
    @invitations = Invitation.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.xml
  def show
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      format.html #show.html.erb
      format.xml  { render :xml => @invitation }
    end
  end

  # GET /invitations/new
  # GET /invitations/new.xml
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invitation }
    end
  end

  # GET /invitations/1/edit
  def edit
    @invitation = Invitation.find(params[:id])
  end

  # POST /invitations
  # POST /invitations.xml
  def create
    @invitation = Invitation.new(params[:invitation])

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to(@invitation, :notice => 'Invitation was successfully created.') }
        format.xml  { render :xml => @invitation, :status => :created, :location => @invitation }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invitation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invitations/1
  # PUT /invitations/1.xml
  def update
    @invitation = Invitation.find(params[:id])

    respond_to do |format|
      if @invitation.update_attributes(params[:invitation])
        format.html { redirect_to(@invitation, :notice => 'Invitation was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @invitation.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1
  # DELETE /invitations/1.xml
  def destroy
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to(invitations_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    @title = "Accueil"
  end

  def contact
    @title = "Contactez-nous"
  end
  
  def about
    @title = "Notre histoire"
  end
  
  def aide
    @title = "Aide"
  end

end

app/helpers/ambiances_helper.rb
module AmbiancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "j-invite-ce-soir"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/ambiances/_form.html.erb
<%= simple_form_for(@ambiance) do |f| %><br />

<%= f.error_messages %>

    <%= f.input :name, :label => 'Ambiance'%><br />

    <%= f.input :description %><br />

    <%= f.button :submit, 'Créer' %><br />

<% end %>

app/views/ambiances/edit.html.erb
<h1>Editing ambiance</h1>

<%= render 'form' %>

<%= link_to 'Voir', @ambiance %> |
<%= link_to 'Retour', ambiances_path %>

app/views/ambiances/index.html.erb
<h1>Listing ambiances</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ambiances.each do |ambiance| %>
  <tr>
    <td><%= ambiance.name %></td>
    <td><%= ambiance.description %></td>
    <td><%= link_to 'Voir', ambiance %></td>
    <td><%= link_to 'Modifier', edit_ambiance_path(ambiance) %></td>
    <td><%= link_to 'Supprimer', ambiance, :confirm => 'Etes-vous sûr?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouvelle ambiance', new_ambiance_path %>

app/views/ambiances/new.html.erb
<h1>Nouvelle ambiance</h1>

<%= render 'form' %>

<%= link_to 'Retour', ambiances_path %>

app/views/ambiances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ambiance :</b>
  <%= @ambiance.name %>
</p>

<p>
  <b>Description :</b>
  <%= @ambiance.description %>
</p>


<%= link_to 'Modifier', edit_ambiance_path(@ambiance) %> |
<%= link_to 'Retour', ambiances_path %>

app/views/cuisines/_form.html.erb
<%= simple_form_for(@cuisine) do |f| %><br />

    <%= f.input :name, :label => 'Nom'%><br />

    <%= f.input :description %><br />

    <%= f.button :submit, 'Créer'%><br />

<% end %>

app/views/cuisines/edit.html.erb
<h1>Modifier votre cuisine</h1>

<%= render 'form' %>

<%= link_to 'Voir', @cuisine %> |
<%= link_to 'Retour', cuisines_path %>

app/views/cuisines/index.html.erb
<h1>Les différentes cuisines</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cuisines.each do |cuisine| %>
  <tr>
    <td><%= cuisine.name %></td>
    <td><%= cuisine.description %></td>
    <td><%= link_to 'Voir', cuisine %></td>
    <td><%= link_to 'Modifier', edit_cuisine_path(cuisine) %></td>
    <td><%= link_to 'Supprimer', cuisine, :confirm => 'Etes-vous sûr?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouvelle cuisine', new_cuisine_path %>

app/views/cuisines/new.html.erb
<h1>Nouvelle cuisine</h1>

<%= render 'form' %>

<%= link_to 'Retour', cuisines_path %>

app/views/cuisines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cuisine :</b>
  <%= @cuisine.name %>
</p>

<p>
  <b>Description :</b>
  <%= @cuisine.description %>
</p>


<%= link_to 'Modifier', edit_cuisine_path(@cuisine) %> |
<%= link_to 'Retour', cuisines_path %>

app/views/invitations/_form.html.erb
<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>

<%= simple_form_for(@invitation) do |f| %><br />

    <%= f.input :name, :label => 'Titre'%><br />

	<%= f.label :date %><br />
	<%= f.text_field :date %><br />

    <%= f.input :description, :as => :text %><br />

    <%= f.input :convives, :collection => 1..100, :include_blank => false, :label => 'Nombre de convives'%><br />

    <%= f.input :price, :collection => 1..100, :include_blank => false, :label => 'Prix', :hint => 'Prix en euros'%><br />
 
    <!--<%= f.input :tag, :label => 'Tag' %><br />-->

    <!--<%= f.input :note, :collection => 1..10, :as => :radio, :include_blank => false, :label => 'Evaluation'%><br />-->

    <!--<%= f.input :comment, :label => 'Commentaire'%><br />-->

	<%= f.association :cuisines, :collection => Cuisine.all(:order => 'name') %>

	<%= f.association :ambiances, :collection => Ambiance.all(:order => 'name')%>

    <%= f.button :submit, 'Créer une invitation' %><br />
 
<% end %>

app/views/invitations/edit.html.erb
<h1>Modifier l'invitation</h1>

<%= render 'form' %>

<%= link_to 'Voir', @invitation %> |
<%= link_to 'Retour', invitations_path %>

app/views/invitations/index.html.erb
<h1>Les différentes invitations en cours</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Description</th>
    <th>Convives</th>
    <th>Price</th>
    <th>Tag</th>
    <th>Note</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.name %></td>
    <td><%= invitation.date %></td>
    <td><%= invitation.description %></td>
    <td><%= invitation.convives %></td>
    <td><%= invitation.price %></td>
    <td><%= invitation.tag %></td>
    <td><%= invitation.note %></td>
    <td><%= invitation.comment %></td>
    <td><%= link_to 'Voir', invitation %></td>
    <td><%= link_to 'Modifier', edit_invitation_path(invitation) %></td>
    <td><%= link_to 'Supprimer', invitation, :confirm => 'Etes-vous sûr?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nouvelle invitation', new_invitation_path %>

app/views/invitations/new.html.erb
<h1>Créer une invitation</h1>

<%= render 'form' %>

<%= link_to 'Retour', invitations_path %>

app/views/invitations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Invitation :</b>
  <%= @invitation.name %>
</p>

<p>
  <b>Date :</b>
  <%= @invitation.date %>
</p>

<p>
  <b>Description:</b>
  <%= @invitation.description %>
</p>

<p>
  <b>Convives :</b>
  <%= @invitation.convives %>
</p>

<p>
  <b>Prix :</b>
  <%= @invitation.price %>
</p>

<p>
  <b>Tag(s) :</b>
  <%= @invitation.tag %>
</p>

<p>
  <b>Evaluation :</b>
  <%= @invitation.note %>
</p>

<p>
  <b>Commentaire :</b>
  <%= @invitation.comment %>
</p>

<p>
	<b>Cuisines :</b>
	<% for cuisines in @invitation.cuisines %>
		<%= cuisines.name %>
	<% end %>
</p>

<p>
	<b>Ambiances :</b>
	<% for ambiances in @invitation.ambiances %>
		<%= ambiances.name %>
	<% end %>
</p>


<%= link_to 'Modifier', edit_invitation_path(@invitation) %> |
<%= link_to 'Retour', invitations_path %>

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Notre histoire", about_path -%></li>
      <li><%= link_to "Aide", aide_path -%></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<% imglogo = image_tag("logo.png", :alt => "stat_app", :class => "round") -%>
<%= link_to imglogo, root_path -%>
<nav class="round">
<ul>
        <li><%= link_to "Accueil", root_path -%></li>
        <li><%= link_to "Contactez-nous", contact_path -%></li>
		<li><%= link_to "Liste des invitations", invitations_path -%></li>
	<div id="user_nav">
		  <% if user_signed_in? %>
		    Signed in as <%= current_user.email %>. Not you?
		    <%= link_to "Déconnexion ", destroy_user_session_path, :method => :delete %>
		  <% else %>
		    <%= link_to "S'inscrire", new_user_registration_path %> or <%= link_to "S'identifier", new_user_session_path %>
		  <% end %>      
	</div>
</ul>
</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application" %>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application" %>
  </head>
  <body>
    <div class="container">
		<%= render 'layouts/header' %>
      	<section class="round">
			<% flash.each do |key, value| %>
			  <div class="flash <%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
      	</section>
		<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
	<head>
	<body>
		<h1> J'invite ce soir | <%= @title -%> </h1>
		<p></br>

		</p>
	</body>
	</head>
</html>

app/views/pages/aide.html.erb
<!DOCTYPE html>
<html>
	<head>
	<body>
		<h1> J'invite ce soir | <%= @title -%></h1>
		<p></br>

		</p>
	</body>
	</head>
</html>

app/views/pages/contact.html.erb
<!DOCTYPE html>
<html>
	<head>
	<body>
		<h1> J'invite ce soir | <%= @title -%> </h1>
		<p></br>

		</p>
	</body>
	</head>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<head>
	<body>
		<h1> J'invite ce soir | <%= @title -%></h1>
		<p></br>

	</body>
	</head>
</html>